image: node:14

# Only run pipelines for merge requests or default branch or tag
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

cache:
  key:
    files:
      - package.json
  paths:
    - node_modules

install-dependencies:
  stage: .pre
  script: yarn install
  rules:
    - if: $CI_MERGE_REQUEST_IID || $CI_COMMIT_TAG || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - package.json
        - yarn.lock

lint:
  script: yarn lint

build:
  script: yarn build
  artifacts:
    paths:
      - '.next'

# api-unit-tests:
#   script: yarn ci:test api --skip-nx-cache
#   artifacts:
#     reports:
#       cobertura: coverage/apps/api/cobertura-coverage.xml
#   after_script:
#     - bash <(curl -s https://codecov.io/bash) -f coverage/apps/api/cobertura-coverage.xml

ui-unit-tests:
  script: yarn test
  artifacts:
    reports:
      cobertura: coverage/ui/cobertura-coverage.xml
  after_script:
    - bash <(curl -s https://codecov.io/bash) -f coverage/ui/cobertura-coverage.xml

staging:
  stage: deploy
  trigger:
    project: wshowair/portfolio-devops
    strategy: depend
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
