image: node:12

# Only run pipelines for merge requests or default branch or tag
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

cache:
  key:
    files:
      - package.json
  paths:
    - node_modules

install-dependencies:
  stage: .pre
  script: yarn install

lint:
  script: yarn ci:lint

build:
  script: yarn ci:build

api-unit-tests:
  script: yarn ci:test api

ui-unit-tests:
  script: yarn ci:test portfolio

api-interfaces-tests:
  script: yarn ci:test api-interfaces
