image: node:12

# Only run pipelines for merge requests or default branch or tag
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

cache:
  key:
    files:
      - package.json
  paths:
    - node_modules

install-dependencies:
  stage: .pre
  script: yarn install

lint:
  script: yarn ci:lint

build:
  script: yarn ci:build

api-unit-tests:
  script: yarn ci:test api
  artifacts:
    reports:
      cobertura: coverage/apps/api/cobertura-coverage.xml

ui-unit-tests:
  script: yarn ci:test portfolio --skip-nx-cache
  artifacts:
    reports:
      cobertura: coverage/apps/portfolio/cobertura-coverage.xml
  after_script:
    - bash <(curl -s https://codecov.io/bash)

api-interfaces-tests:
  script: yarn ci:test api-interfaces
