name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependencies:
    env:
      NODE_VERSION: 14.15.1
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'
    - run: yarn install --frozen-lockfile

  lint:
    needs: [dependencies]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: yarn lint

  test:
    needs: [dependencies]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: yarn test

  build:
    needs: [dependencies]
    runs-on: ubuntu-20.04
    steps:
    - run: yarn build

  dockerize:
    needs: [lint, test, build]
    env: 
      SHA: ${{github.event.pull_request.head.sha || github.sha}}
    runs-on: ubuntu-20.04
    steps:
    - name: Set SHA_SHORT
      run: |
        echo "SHA_SHORT=$(echo ${{env.SHA}} | cut -c1-7 )" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag portfolio:${{env.SHA_SHORT}}
