name: ci

on: push
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  dockerizePR:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      if: $GITHUB_EVENT_NAME == 'pull_request'
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag portfolio:${{ github.event.pull_request.head.sha }}

  dockerize:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      if: $GITHUB_EVENT_NAME == 'push' && $GITHUB_REF_NAME === 'pipeline'
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag portfolio:$GITHUB_SHA
