name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RUNNER_TYPE: ubuntu-20.04
  NODE_VERSION: 14.15.1

jobs:
  build:
    runs-on: ${{env.RUNNER_TYPE}}
    container:
      image: node:${{ env.NODE_VERSION }}-alpine3.12
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'
    - run: yarn install --frozen-lockfile
    - run: yarn lint
    - run: yarn build
    - run: yarn test

  dockerize:
    needs: build
    env: 
      SHA: ${{github.event.pull_request.head.sha || github.sha}}
    runs-on: ${{env.RUNNER_TYPE}}
    container:
      image: node:${{ env.NODE_VERSION }}-alpine3.12
    steps:
    - name: Set SHA_SHORT
      run: |
        echo "SHA_SHORT=$(echo ${{env.SHA}} | cut -c1-7 )" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - name: install prod dependencies
      run: yarn install --production --frozen-lockfile # prune dev dependencies
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag portfolio:${{env.SHA_SHORT}}
