name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      NODE_VERSION: 14.15.1
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'
    - run: yarn install --frozen-lockfile
    - run: yarn lint
    - run: yarn build
    - run: yarn test

  dockerize:
    # needs: build
    env:
      CONTAINER_REGISTRY: ghcr.io
      CONTAINER_REPOSITORY: ${{ github.repository }}
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v1
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.CONTAINER_REGISTRY }}/${{ env.CONTAINER_REPOSITORY }}
        labels: |
          org.opencontainers.image.description=deployable image for my portfolio
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr
          type=sha
    - name: Build Container image
      uses: docker/build-push-action@v2
      with:
        platforms: linux/arm64
        push: false
    - name: Push Container image
      uses: docker/build-push-action@v2
      with:
        platforms: linux/arm64
        push: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
