name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # dockerizePR:
  #   if: github.event_name == 'pull_request'
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #     with:
  #       ref: ${{ github.event.pull_request.head.sha }}
  #   - name: Build the Docker image
  #     run: docker build . --file Dockerfile --tag portfolio:${{ github.event.pull_request.head.sha }}

  dockerize:
    env: 
      SHA: ${{github.event.pull_request.head.sha || github.sha}}
      # SHA_SHORT: ${{}}
    if: github.event_name == 'push' && github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag portfolio:${{env.SHA}}
